import {
  BotMessageSquare,
  CheckIcon,
  Clock,
  GoalIcon,
  MailIcon,
  MapIcon,
  MapPin,
  Pencil,
  PhoneIcon,
  SearchIcon,
  UserCircleIcon,
  X,
  UserCircle,
  CarIcon,
  CheckCircle,
  SparklesIcon,
  UserIcon,
  ArrowRight,
  PlusCircleIcon,
  RotateCw,
  Upload,
  ArrowDown,
  ArrowUp,
  MoreHorizontal,
  Trash2,
  Trash,
  Edit,
  ArrowLeft,
  QrCode,
  CalendarX2,
  Loader2,
  KeySquare,
  LogOutIcon,
  CheckCircle2,
  ChevronsUpDown,
  Calendar,
  CalendarClock,
  Car,
  AlertTriangle,
  Map,
  Settings,
  CreditCard,
  Building2,
  Globe,
  Copy,
  PanelLeft,
  PlusCircle,
  SettingsIcon,
  ChevronRight,
  Plus,
  Coins,
  ReceiptText
} from 'lucide-react';
import Image from "next/image"
import { cn } from '@/utils/ui';

export const icons = [
  { label: 'AlertTriangle', value: 'AlertTriangle', icon: AlertTriangle },
  { label: 'ArrowDown', value: 'ArrowDown', icon: ArrowDown },
  { label: 'ArrowLeft', value: 'ArrowLeft', icon: ArrowLeft },
  { label: 'ArrowRight', value: 'ArrowRight', icon: ArrowRight },
  { label: 'ArrowUp', value: 'ArrowUp', icon: ArrowUp },
  { label: 'BotMessageSquare', value: 'BotMessageSquare', icon: BotMessageSquare },
  { label: 'Building2', value: 'Building2', icon: Building2 },
  { label: 'Calendar', value: 'Calendar', icon: Calendar },
  { label: 'CalendarClock', value: 'CalendarClock', icon: CalendarClock },
  { label: 'CalendarX2', value: 'CalendarX2', icon: CalendarX2 },
  { label: 'Car', value: 'Car', icon: Car },
  { label: 'CarIcon', value: 'CarIcon', icon: CarIcon },
  { label: 'CheckCircle', value: 'CheckCircle', icon: CheckCircle },
  { label: 'CheckCircle2', value: 'CheckCircle2', icon: CheckCircle2 },
  { label: 'CheckIcon', value: 'CheckIcon', icon: CheckIcon },
  { label: 'ChevronRight', value: 'ChevronRight', icon: ChevronRight },
  { label: 'ChevronsUpDown', value: 'ChevronsUpDown', icon: ChevronsUpDown },
  { label: 'Clock', value: 'Clock', icon: Clock },
  { label: 'Copy', value: 'Copy', icon: Copy },
  { label: 'Coins', value: 'Coins', icon: Coins },
  { label: 'CreditCard', value: 'CreditCard', icon: CreditCard },
  { label: 'Edit', value: 'Edit', icon: Edit },
  { label: 'Globe', value: 'Globe', icon: Globe },
  { label: 'GoalIcon', value: 'GoalIcon', icon: GoalIcon },
  { label: 'KeySquare', value: 'KeySquare', icon: KeySquare },
  { label: 'Loader2', value: 'Loader2', icon: Loader2 },
  { label: 'LogOutIcon', value: 'LogOutIcon', icon: LogOutIcon },
  { label: 'MailIcon', value: 'MailIcon', icon: MailIcon },
  { label: 'Map', value: 'Map', icon: Map },
  { label: 'MapIcon', value: 'MapIcon', icon: MapIcon },
  { label: 'MapPin', value: 'MapPin', icon: MapPin },
  { label: 'MoreHorizontal', value: 'MoreHorizontal', icon: MoreHorizontal },
  { label: 'PanelLeft', value: 'PanelLeft', icon: PanelLeft },
  { label: 'Pencil', value: 'Pencil', icon: Pencil },
  { label: 'PhoneIcon', value: 'PhoneIcon', icon: PhoneIcon },
  { label: 'Plus', value: 'Plus', icon: Plus },
  { label: 'PlusCircle', value: 'PlusCircle', icon: PlusCircle },
  { label: 'PlusCircleIcon', value: 'PlusCircleIcon', icon: PlusCircleIcon },
  { label: 'QrCode', value: 'QrCode', icon: QrCode },
  { label: 'ReceiptText', value: 'ReceiptText', icon: ReceiptText },
  { label: 'RotateCw', value: 'RotateCw', icon: RotateCw },
  { label: 'SearchIcon', value: 'SearchIcon', icon: SearchIcon },
  { label: 'Settings', value: 'Settings', icon: Settings },
  { label: 'SettingsIcon', value: 'SettingsIcon', icon: SettingsIcon },
  { label: 'SparklesIcon', value: 'SparklesIcon', icon: SparklesIcon },
  { label: 'Trash', value: 'Trash', icon: Trash },
  { label: 'Trash2', value: 'Trash2', icon: Trash2 },
  { label: 'Upload', value: 'Upload', icon: Upload },
  { label: 'UserCircle', value: 'UserCircle', icon: UserCircle },
  { label: 'UserCircleIcon', value: 'UserCircleIcon', icon: UserCircleIcon },
  { label: 'UserIcon', value: 'UserIcon', icon: UserIcon },
  { label: 'X', value: 'X', icon: X }
];

export const WhatsappIcon = ({ className = "" }: { className?: string }) => {
  return (
    <Image src={'images/whatsapp-logo.png'} height={100} width={100}
      className={cn("h-4 w-4 text-white object-cover", className)} alt={"Logo Whatsapp"} />
  )
} 